// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ClientCommandBuff.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "proto/ClientCommandBuff.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* ClientCommandBuff_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ClientCommandBuff_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_proto_2fClientCommandBuff_2eproto() {
  protobuf_AddDesc_proto_2fClientCommandBuff_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "proto/ClientCommandBuff.proto");
  GOOGLE_CHECK(file != NULL);
  ClientCommandBuff_descriptor_ = file->message_type(0);
  static const int ClientCommandBuff_offsets_[1] = {
  };
  ClientCommandBuff_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ClientCommandBuff_descriptor_,
      ClientCommandBuff::default_instance_,
      ClientCommandBuff_offsets_,
      -1,
      -1,
      -1,
      sizeof(ClientCommandBuff),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientCommandBuff, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientCommandBuff, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_proto_2fClientCommandBuff_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ClientCommandBuff_descriptor_, &ClientCommandBuff::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_proto_2fClientCommandBuff_2eproto() {
  delete ClientCommandBuff::default_instance_;
  delete ClientCommandBuff_reflection_;
}

void protobuf_AddDesc_proto_2fClientCommandBuff_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\035proto/ClientCommandBuff.proto\"\023\n\021Clien"
    "tCommandBuffb\006proto3", 60);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "proto/ClientCommandBuff.proto", &protobuf_RegisterTypes);
  ClientCommandBuff::default_instance_ = new ClientCommandBuff();
  ClientCommandBuff::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_proto_2fClientCommandBuff_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_proto_2fClientCommandBuff_2eproto {
  StaticDescriptorInitializer_proto_2fClientCommandBuff_2eproto() {
    protobuf_AddDesc_proto_2fClientCommandBuff_2eproto();
  }
} static_descriptor_initializer_proto_2fClientCommandBuff_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ClientCommandBuff::ClientCommandBuff()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:ClientCommandBuff)
}

void ClientCommandBuff::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

ClientCommandBuff::ClientCommandBuff(const ClientCommandBuff& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:ClientCommandBuff)
}

void ClientCommandBuff::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

ClientCommandBuff::~ClientCommandBuff() {
  // @@protoc_insertion_point(destructor:ClientCommandBuff)
  SharedDtor();
}

void ClientCommandBuff::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ClientCommandBuff::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ClientCommandBuff::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ClientCommandBuff_descriptor_;
}

const ClientCommandBuff& ClientCommandBuff::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_proto_2fClientCommandBuff_2eproto();
  return *default_instance_;
}

ClientCommandBuff* ClientCommandBuff::default_instance_ = NULL;

ClientCommandBuff* ClientCommandBuff::New(::google::protobuf::Arena* arena) const {
  ClientCommandBuff* n = new ClientCommandBuff;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ClientCommandBuff::Clear() {
}

bool ClientCommandBuff::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ClientCommandBuff)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0 ||
        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
  }
success:
  // @@protoc_insertion_point(parse_success:ClientCommandBuff)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ClientCommandBuff)
  return false;
#undef DO_
}

void ClientCommandBuff::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ClientCommandBuff)
  // @@protoc_insertion_point(serialize_end:ClientCommandBuff)
}

::google::protobuf::uint8* ClientCommandBuff::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:ClientCommandBuff)
  // @@protoc_insertion_point(serialize_to_array_end:ClientCommandBuff)
  return target;
}

int ClientCommandBuff::ByteSize() const {
  int total_size = 0;

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ClientCommandBuff::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const ClientCommandBuff* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const ClientCommandBuff>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ClientCommandBuff::MergeFrom(const ClientCommandBuff& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
}

void ClientCommandBuff::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ClientCommandBuff::CopyFrom(const ClientCommandBuff& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ClientCommandBuff::IsInitialized() const {

  return true;
}

void ClientCommandBuff::Swap(ClientCommandBuff* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ClientCommandBuff::InternalSwap(ClientCommandBuff* other) {
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ClientCommandBuff::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ClientCommandBuff_descriptor_;
  metadata.reflection = ClientCommandBuff_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ClientCommandBuff

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
