// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/CommandBuff.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "proto/CommandBuff.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* CommandBuff_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CommandBuff_reflection_ = NULL;
struct CommandBuffOneofInstance {
  const ::SetValueSubCommand* setvaluesubcommand_;
  const ::ManagerSubCommand* managersubcommand_;
  const ::SystemSubCommand* systemsubcommand_;
}* CommandBuff_default_oneof_instance_ = NULL;

}  // namespace


void protobuf_AssignDesc_proto_2fCommandBuff_2eproto() {
  protobuf_AddDesc_proto_2fCommandBuff_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "proto/CommandBuff.proto");
  GOOGLE_CHECK(file != NULL);
  CommandBuff_descriptor_ = file->message_type(0);
  static const int CommandBuff_offsets_[4] = {
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(CommandBuff_default_oneof_instance_, setvaluesubcommand_),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(CommandBuff_default_oneof_instance_, managersubcommand_),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(CommandBuff_default_oneof_instance_, systemsubcommand_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommandBuff, subCommand_),
  };
  CommandBuff_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      CommandBuff_descriptor_,
      CommandBuff::default_instance_,
      CommandBuff_offsets_,
      -1,
      -1,
      -1,
      CommandBuff_default_oneof_instance_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommandBuff, _oneof_case_[0]),
      sizeof(CommandBuff),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommandBuff, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommandBuff, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_proto_2fCommandBuff_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      CommandBuff_descriptor_, &CommandBuff::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_proto_2fCommandBuff_2eproto() {
  delete CommandBuff::default_instance_;
  delete CommandBuff_default_oneof_instance_;
  delete CommandBuff_reflection_;
}

void protobuf_AddDesc_proto_2fCommandBuff_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::protobuf_AddDesc_proto_2fSetValueSubCommand_2eproto();
  ::protobuf_AddDesc_proto_2fSystemSubCommand_2eproto();
  ::protobuf_AddDesc_proto_2fManagerSubCommand_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\027proto/CommandBuff.proto\032\036proto/SetValu"
    "eSubCommand.proto\032\034proto/SystemSubComman"
    "d.proto\032\035proto/ManagerSubCommand.proto\"\256"
    "\001\n\013CommandBuff\0221\n\022setValueSubCommand\030\001 \001"
    "(\0132\023.SetValueSubCommandH\000\022/\n\021managerSubC"
    "ommand\030\002 \001(\0132\022.ManagerSubCommandH\000\022-\n\020Sy"
    "stemSubCommand\030\003 \001(\0132\021.SystemSubCommandH"
    "\000B\014\n\nsubCommandb\006proto3", 303);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "proto/CommandBuff.proto", &protobuf_RegisterTypes);
  CommandBuff::default_instance_ = new CommandBuff();
  CommandBuff_default_oneof_instance_ = new CommandBuffOneofInstance();
  CommandBuff::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_proto_2fCommandBuff_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_proto_2fCommandBuff_2eproto {
  StaticDescriptorInitializer_proto_2fCommandBuff_2eproto() {
    protobuf_AddDesc_proto_2fCommandBuff_2eproto();
  }
} static_descriptor_initializer_proto_2fCommandBuff_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CommandBuff::kSetValueSubCommandFieldNumber;
const int CommandBuff::kManagerSubCommandFieldNumber;
const int CommandBuff::kSystemSubCommandFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CommandBuff::CommandBuff()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:CommandBuff)
}

void CommandBuff::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  CommandBuff_default_oneof_instance_->setvaluesubcommand_ = const_cast< ::SetValueSubCommand*>(&::SetValueSubCommand::default_instance());
  CommandBuff_default_oneof_instance_->managersubcommand_ = const_cast< ::ManagerSubCommand*>(&::ManagerSubCommand::default_instance());
  CommandBuff_default_oneof_instance_->systemsubcommand_ = const_cast< ::SystemSubCommand*>(&::SystemSubCommand::default_instance());
}

CommandBuff::CommandBuff(const CommandBuff& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:CommandBuff)
}

void CommandBuff::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  clear_has_subCommand();
}

CommandBuff::~CommandBuff() {
  // @@protoc_insertion_point(destructor:CommandBuff)
  SharedDtor();
}

void CommandBuff::SharedDtor() {
  if (has_subCommand()) {
    clear_subCommand();
  }
  if (this != default_instance_) {
  }
}

void CommandBuff::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CommandBuff::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CommandBuff_descriptor_;
}

const CommandBuff& CommandBuff::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_proto_2fCommandBuff_2eproto();
  return *default_instance_;
}

CommandBuff* CommandBuff::default_instance_ = NULL;

CommandBuff* CommandBuff::New(::google::protobuf::Arena* arena) const {
  CommandBuff* n = new CommandBuff;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CommandBuff::clear_subCommand() {
  switch(subCommand_case()) {
    case kSetValueSubCommand: {
      delete subCommand_.setvaluesubcommand_;
      break;
    }
    case kManagerSubCommand: {
      delete subCommand_.managersubcommand_;
      break;
    }
    case kSystemSubCommand: {
      delete subCommand_.systemsubcommand_;
      break;
    }
    case SUBCOMMAND_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = SUBCOMMAND_NOT_SET;
}


void CommandBuff::Clear() {
  clear_subCommand();
}

bool CommandBuff::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CommandBuff)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .SetValueSubCommand setValueSubCommand = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_setvaluesubcommand()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_managerSubCommand;
        break;
      }

      // optional .ManagerSubCommand managerSubCommand = 2;
      case 2: {
        if (tag == 18) {
         parse_managerSubCommand:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_managersubcommand()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_SystemSubCommand;
        break;
      }

      // optional .SystemSubCommand SystemSubCommand = 3;
      case 3: {
        if (tag == 26) {
         parse_SystemSubCommand:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_systemsubcommand()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CommandBuff)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CommandBuff)
  return false;
#undef DO_
}

void CommandBuff::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CommandBuff)
  // optional .SetValueSubCommand setValueSubCommand = 1;
  if (has_setvaluesubcommand()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *subCommand_.setvaluesubcommand_, output);
  }

  // optional .ManagerSubCommand managerSubCommand = 2;
  if (has_managersubcommand()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *subCommand_.managersubcommand_, output);
  }

  // optional .SystemSubCommand SystemSubCommand = 3;
  if (has_systemsubcommand()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, *subCommand_.systemsubcommand_, output);
  }

  // @@protoc_insertion_point(serialize_end:CommandBuff)
}

::google::protobuf::uint8* CommandBuff::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:CommandBuff)
  // optional .SetValueSubCommand setValueSubCommand = 1;
  if (has_setvaluesubcommand()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, *subCommand_.setvaluesubcommand_, target);
  }

  // optional .ManagerSubCommand managerSubCommand = 2;
  if (has_managersubcommand()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, *subCommand_.managersubcommand_, target);
  }

  // optional .SystemSubCommand SystemSubCommand = 3;
  if (has_systemsubcommand()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, *subCommand_.systemsubcommand_, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:CommandBuff)
  return target;
}

int CommandBuff::ByteSize() const {
  int total_size = 0;

  switch (subCommand_case()) {
    // optional .SetValueSubCommand setValueSubCommand = 1;
    case kSetValueSubCommand: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *subCommand_.setvaluesubcommand_);
      break;
    }
    // optional .ManagerSubCommand managerSubCommand = 2;
    case kManagerSubCommand: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *subCommand_.managersubcommand_);
      break;
    }
    // optional .SystemSubCommand SystemSubCommand = 3;
    case kSystemSubCommand: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *subCommand_.systemsubcommand_);
      break;
    }
    case SUBCOMMAND_NOT_SET: {
      break;
    }
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CommandBuff::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const CommandBuff* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const CommandBuff>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CommandBuff::MergeFrom(const CommandBuff& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  switch (from.subCommand_case()) {
    case kSetValueSubCommand: {
      mutable_setvaluesubcommand()->::SetValueSubCommand::MergeFrom(from.setvaluesubcommand());
      break;
    }
    case kManagerSubCommand: {
      mutable_managersubcommand()->::ManagerSubCommand::MergeFrom(from.managersubcommand());
      break;
    }
    case kSystemSubCommand: {
      mutable_systemsubcommand()->::SystemSubCommand::MergeFrom(from.systemsubcommand());
      break;
    }
    case SUBCOMMAND_NOT_SET: {
      break;
    }
  }
}

void CommandBuff::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CommandBuff::CopyFrom(const CommandBuff& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CommandBuff::IsInitialized() const {

  return true;
}

void CommandBuff::Swap(CommandBuff* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CommandBuff::InternalSwap(CommandBuff* other) {
  std::swap(subCommand_, other->subCommand_);
  std::swap(_oneof_case_[0], other->_oneof_case_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CommandBuff::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CommandBuff_descriptor_;
  metadata.reflection = CommandBuff_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CommandBuff

// optional .SetValueSubCommand setValueSubCommand = 1;
bool CommandBuff::has_setvaluesubcommand() const {
  return subCommand_case() == kSetValueSubCommand;
}
void CommandBuff::set_has_setvaluesubcommand() {
  _oneof_case_[0] = kSetValueSubCommand;
}
void CommandBuff::clear_setvaluesubcommand() {
  if (has_setvaluesubcommand()) {
    delete subCommand_.setvaluesubcommand_;
    clear_has_subCommand();
  }
}
 const ::SetValueSubCommand& CommandBuff::setvaluesubcommand() const {
  // @@protoc_insertion_point(field_get:CommandBuff.setValueSubCommand)
  return has_setvaluesubcommand()
      ? *subCommand_.setvaluesubcommand_
      : ::SetValueSubCommand::default_instance();
}
::SetValueSubCommand* CommandBuff::mutable_setvaluesubcommand() {
  if (!has_setvaluesubcommand()) {
    clear_subCommand();
    set_has_setvaluesubcommand();
    subCommand_.setvaluesubcommand_ = new ::SetValueSubCommand;
  }
  // @@protoc_insertion_point(field_mutable:CommandBuff.setValueSubCommand)
  return subCommand_.setvaluesubcommand_;
}
::SetValueSubCommand* CommandBuff::release_setvaluesubcommand() {
  if (has_setvaluesubcommand()) {
    clear_has_subCommand();
    ::SetValueSubCommand* temp = subCommand_.setvaluesubcommand_;
    subCommand_.setvaluesubcommand_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
void CommandBuff::set_allocated_setvaluesubcommand(::SetValueSubCommand* setvaluesubcommand) {
  clear_subCommand();
  if (setvaluesubcommand) {
    set_has_setvaluesubcommand();
    subCommand_.setvaluesubcommand_ = setvaluesubcommand;
  }
  // @@protoc_insertion_point(field_set_allocated:CommandBuff.setValueSubCommand)
}

// optional .ManagerSubCommand managerSubCommand = 2;
bool CommandBuff::has_managersubcommand() const {
  return subCommand_case() == kManagerSubCommand;
}
void CommandBuff::set_has_managersubcommand() {
  _oneof_case_[0] = kManagerSubCommand;
}
void CommandBuff::clear_managersubcommand() {
  if (has_managersubcommand()) {
    delete subCommand_.managersubcommand_;
    clear_has_subCommand();
  }
}
 const ::ManagerSubCommand& CommandBuff::managersubcommand() const {
  // @@protoc_insertion_point(field_get:CommandBuff.managerSubCommand)
  return has_managersubcommand()
      ? *subCommand_.managersubcommand_
      : ::ManagerSubCommand::default_instance();
}
::ManagerSubCommand* CommandBuff::mutable_managersubcommand() {
  if (!has_managersubcommand()) {
    clear_subCommand();
    set_has_managersubcommand();
    subCommand_.managersubcommand_ = new ::ManagerSubCommand;
  }
  // @@protoc_insertion_point(field_mutable:CommandBuff.managerSubCommand)
  return subCommand_.managersubcommand_;
}
::ManagerSubCommand* CommandBuff::release_managersubcommand() {
  if (has_managersubcommand()) {
    clear_has_subCommand();
    ::ManagerSubCommand* temp = subCommand_.managersubcommand_;
    subCommand_.managersubcommand_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
void CommandBuff::set_allocated_managersubcommand(::ManagerSubCommand* managersubcommand) {
  clear_subCommand();
  if (managersubcommand) {
    set_has_managersubcommand();
    subCommand_.managersubcommand_ = managersubcommand;
  }
  // @@protoc_insertion_point(field_set_allocated:CommandBuff.managerSubCommand)
}

// optional .SystemSubCommand SystemSubCommand = 3;
bool CommandBuff::has_systemsubcommand() const {
  return subCommand_case() == kSystemSubCommand;
}
void CommandBuff::set_has_systemsubcommand() {
  _oneof_case_[0] = kSystemSubCommand;
}
void CommandBuff::clear_systemsubcommand() {
  if (has_systemsubcommand()) {
    delete subCommand_.systemsubcommand_;
    clear_has_subCommand();
  }
}
 const ::SystemSubCommand& CommandBuff::systemsubcommand() const {
  // @@protoc_insertion_point(field_get:CommandBuff.SystemSubCommand)
  return has_systemsubcommand()
      ? *subCommand_.systemsubcommand_
      : ::SystemSubCommand::default_instance();
}
::SystemSubCommand* CommandBuff::mutable_systemsubcommand() {
  if (!has_systemsubcommand()) {
    clear_subCommand();
    set_has_systemsubcommand();
    subCommand_.systemsubcommand_ = new ::SystemSubCommand;
  }
  // @@protoc_insertion_point(field_mutable:CommandBuff.SystemSubCommand)
  return subCommand_.systemsubcommand_;
}
::SystemSubCommand* CommandBuff::release_systemsubcommand() {
  if (has_systemsubcommand()) {
    clear_has_subCommand();
    ::SystemSubCommand* temp = subCommand_.systemsubcommand_;
    subCommand_.systemsubcommand_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
void CommandBuff::set_allocated_systemsubcommand(::SystemSubCommand* systemsubcommand) {
  clear_subCommand();
  if (systemsubcommand) {
    set_has_systemsubcommand();
    subCommand_.systemsubcommand_ = systemsubcommand;
  }
  // @@protoc_insertion_point(field_set_allocated:CommandBuff.SystemSubCommand)
}

bool CommandBuff::has_subCommand() const {
  return subCommand_case() != SUBCOMMAND_NOT_SET;
}
void CommandBuff::clear_has_subCommand() {
  _oneof_case_[0] = SUBCOMMAND_NOT_SET;
}
CommandBuff::SubCommandCase CommandBuff::subCommand_case() const {
  return CommandBuff::SubCommandCase(_oneof_case_[0]);
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
