// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/CommandBuff.proto

#ifndef PROTOBUF_proto_2fCommandBuff_2eproto__INCLUDED
#define PROTOBUF_proto_2fCommandBuff_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "proto/SetValueSubCommand.pb.h"
#include "proto/SystemSubCommand.pb.h"
#include "proto/ManagerSubCommand.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_proto_2fCommandBuff_2eproto();
void protobuf_AssignDesc_proto_2fCommandBuff_2eproto();
void protobuf_ShutdownFile_proto_2fCommandBuff_2eproto();

class CommandBuff;

// ===================================================================

class CommandBuff : public ::google::protobuf::Message {
 public:
  CommandBuff();
  virtual ~CommandBuff();

  CommandBuff(const CommandBuff& from);

  inline CommandBuff& operator=(const CommandBuff& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CommandBuff& default_instance();

  enum SubCommandCase {
    kSetValueSubCommand = 1,
    kManagerSubCommand = 2,
    kSystemSubCommand = 3,
    SUBCOMMAND_NOT_SET = 0,
  };

  void Swap(CommandBuff* other);

  // implements Message ----------------------------------------------

  inline CommandBuff* New() const { return New(NULL); }

  CommandBuff* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CommandBuff& from);
  void MergeFrom(const CommandBuff& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CommandBuff* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .SetValueSubCommand setValueSubCommand = 1;
  bool has_setvaluesubcommand() const;
  void clear_setvaluesubcommand();
  static const int kSetValueSubCommandFieldNumber = 1;
  const ::SetValueSubCommand& setvaluesubcommand() const;
  ::SetValueSubCommand* mutable_setvaluesubcommand();
  ::SetValueSubCommand* release_setvaluesubcommand();
  void set_allocated_setvaluesubcommand(::SetValueSubCommand* setvaluesubcommand);

  // optional .ManagerSubCommand managerSubCommand = 2;
  bool has_managersubcommand() const;
  void clear_managersubcommand();
  static const int kManagerSubCommandFieldNumber = 2;
  const ::ManagerSubCommand& managersubcommand() const;
  ::ManagerSubCommand* mutable_managersubcommand();
  ::ManagerSubCommand* release_managersubcommand();
  void set_allocated_managersubcommand(::ManagerSubCommand* managersubcommand);

  // optional .SystemSubCommand SystemSubCommand = 3;
  bool has_systemsubcommand() const;
  void clear_systemsubcommand();
  static const int kSystemSubCommandFieldNumber = 3;
  const ::SystemSubCommand& systemsubcommand() const;
  ::SystemSubCommand* mutable_systemsubcommand();
  ::SystemSubCommand* release_systemsubcommand();
  void set_allocated_systemsubcommand(::SystemSubCommand* systemsubcommand);

  SubCommandCase subCommand_case() const;
  // @@protoc_insertion_point(class_scope:CommandBuff)
 private:
  inline void set_has_setvaluesubcommand();
  inline void set_has_managersubcommand();
  inline void set_has_systemsubcommand();

  inline bool has_subCommand() const;
  void clear_subCommand();
  inline void clear_has_subCommand();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  union SubCommandUnion {
    SubCommandUnion() {}
    ::SetValueSubCommand* setvaluesubcommand_;
    ::ManagerSubCommand* managersubcommand_;
    ::SystemSubCommand* systemsubcommand_;
  } subCommand_;
  mutable int _cached_size_;
  ::google::protobuf::uint32 _oneof_case_[1];

  friend void  protobuf_AddDesc_proto_2fCommandBuff_2eproto();
  friend void protobuf_AssignDesc_proto_2fCommandBuff_2eproto();
  friend void protobuf_ShutdownFile_proto_2fCommandBuff_2eproto();

  void InitAsDefaultInstance();
  static CommandBuff* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// CommandBuff

// optional .SetValueSubCommand setValueSubCommand = 1;
inline bool CommandBuff::has_setvaluesubcommand() const {
  return subCommand_case() == kSetValueSubCommand;
}
inline void CommandBuff::set_has_setvaluesubcommand() {
  _oneof_case_[0] = kSetValueSubCommand;
}
inline void CommandBuff::clear_setvaluesubcommand() {
  if (has_setvaluesubcommand()) {
    delete subCommand_.setvaluesubcommand_;
    clear_has_subCommand();
  }
}
inline  const ::SetValueSubCommand& CommandBuff::setvaluesubcommand() const {
  // @@protoc_insertion_point(field_get:CommandBuff.setValueSubCommand)
  return has_setvaluesubcommand()
      ? *subCommand_.setvaluesubcommand_
      : ::SetValueSubCommand::default_instance();
}
inline ::SetValueSubCommand* CommandBuff::mutable_setvaluesubcommand() {
  if (!has_setvaluesubcommand()) {
    clear_subCommand();
    set_has_setvaluesubcommand();
    subCommand_.setvaluesubcommand_ = new ::SetValueSubCommand;
  }
  // @@protoc_insertion_point(field_mutable:CommandBuff.setValueSubCommand)
  return subCommand_.setvaluesubcommand_;
}
inline ::SetValueSubCommand* CommandBuff::release_setvaluesubcommand() {
  if (has_setvaluesubcommand()) {
    clear_has_subCommand();
    ::SetValueSubCommand* temp = subCommand_.setvaluesubcommand_;
    subCommand_.setvaluesubcommand_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void CommandBuff::set_allocated_setvaluesubcommand(::SetValueSubCommand* setvaluesubcommand) {
  clear_subCommand();
  if (setvaluesubcommand) {
    set_has_setvaluesubcommand();
    subCommand_.setvaluesubcommand_ = setvaluesubcommand;
  }
  // @@protoc_insertion_point(field_set_allocated:CommandBuff.setValueSubCommand)
}

// optional .ManagerSubCommand managerSubCommand = 2;
inline bool CommandBuff::has_managersubcommand() const {
  return subCommand_case() == kManagerSubCommand;
}
inline void CommandBuff::set_has_managersubcommand() {
  _oneof_case_[0] = kManagerSubCommand;
}
inline void CommandBuff::clear_managersubcommand() {
  if (has_managersubcommand()) {
    delete subCommand_.managersubcommand_;
    clear_has_subCommand();
  }
}
inline  const ::ManagerSubCommand& CommandBuff::managersubcommand() const {
  // @@protoc_insertion_point(field_get:CommandBuff.managerSubCommand)
  return has_managersubcommand()
      ? *subCommand_.managersubcommand_
      : ::ManagerSubCommand::default_instance();
}
inline ::ManagerSubCommand* CommandBuff::mutable_managersubcommand() {
  if (!has_managersubcommand()) {
    clear_subCommand();
    set_has_managersubcommand();
    subCommand_.managersubcommand_ = new ::ManagerSubCommand;
  }
  // @@protoc_insertion_point(field_mutable:CommandBuff.managerSubCommand)
  return subCommand_.managersubcommand_;
}
inline ::ManagerSubCommand* CommandBuff::release_managersubcommand() {
  if (has_managersubcommand()) {
    clear_has_subCommand();
    ::ManagerSubCommand* temp = subCommand_.managersubcommand_;
    subCommand_.managersubcommand_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void CommandBuff::set_allocated_managersubcommand(::ManagerSubCommand* managersubcommand) {
  clear_subCommand();
  if (managersubcommand) {
    set_has_managersubcommand();
    subCommand_.managersubcommand_ = managersubcommand;
  }
  // @@protoc_insertion_point(field_set_allocated:CommandBuff.managerSubCommand)
}

// optional .SystemSubCommand SystemSubCommand = 3;
inline bool CommandBuff::has_systemsubcommand() const {
  return subCommand_case() == kSystemSubCommand;
}
inline void CommandBuff::set_has_systemsubcommand() {
  _oneof_case_[0] = kSystemSubCommand;
}
inline void CommandBuff::clear_systemsubcommand() {
  if (has_systemsubcommand()) {
    delete subCommand_.systemsubcommand_;
    clear_has_subCommand();
  }
}
inline  const ::SystemSubCommand& CommandBuff::systemsubcommand() const {
  // @@protoc_insertion_point(field_get:CommandBuff.SystemSubCommand)
  return has_systemsubcommand()
      ? *subCommand_.systemsubcommand_
      : ::SystemSubCommand::default_instance();
}
inline ::SystemSubCommand* CommandBuff::mutable_systemsubcommand() {
  if (!has_systemsubcommand()) {
    clear_subCommand();
    set_has_systemsubcommand();
    subCommand_.systemsubcommand_ = new ::SystemSubCommand;
  }
  // @@protoc_insertion_point(field_mutable:CommandBuff.SystemSubCommand)
  return subCommand_.systemsubcommand_;
}
inline ::SystemSubCommand* CommandBuff::release_systemsubcommand() {
  if (has_systemsubcommand()) {
    clear_has_subCommand();
    ::SystemSubCommand* temp = subCommand_.systemsubcommand_;
    subCommand_.systemsubcommand_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void CommandBuff::set_allocated_systemsubcommand(::SystemSubCommand* systemsubcommand) {
  clear_subCommand();
  if (systemsubcommand) {
    set_has_systemsubcommand();
    subCommand_.systemsubcommand_ = systemsubcommand;
  }
  // @@protoc_insertion_point(field_set_allocated:CommandBuff.SystemSubCommand)
}

inline bool CommandBuff::has_subCommand() const {
  return subCommand_case() != SUBCOMMAND_NOT_SET;
}
inline void CommandBuff::clear_has_subCommand() {
  _oneof_case_[0] = SUBCOMMAND_NOT_SET;
}
inline CommandBuff::SubCommandCase CommandBuff::subCommand_case() const {
  return CommandBuff::SubCommandCase(_oneof_case_[0]);
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_proto_2fCommandBuff_2eproto__INCLUDED
