// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/GetResourceSubCommand.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "proto/GetResourceSubCommand.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* GetResourceSubCommand_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  GetResourceSubCommand_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_proto_2fGetResourceSubCommand_2eproto() {
  protobuf_AddDesc_proto_2fGetResourceSubCommand_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "proto/GetResourceSubCommand.proto");
  GOOGLE_CHECK(file != NULL);
  GetResourceSubCommand_descriptor_ = file->message_type(0);
  static const int GetResourceSubCommand_offsets_[1] = {
  };
  GetResourceSubCommand_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      GetResourceSubCommand_descriptor_,
      GetResourceSubCommand::default_instance_,
      GetResourceSubCommand_offsets_,
      -1,
      -1,
      -1,
      sizeof(GetResourceSubCommand),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetResourceSubCommand, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetResourceSubCommand, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_proto_2fGetResourceSubCommand_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      GetResourceSubCommand_descriptor_, &GetResourceSubCommand::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_proto_2fGetResourceSubCommand_2eproto() {
  delete GetResourceSubCommand::default_instance_;
  delete GetResourceSubCommand_reflection_;
}

void protobuf_AddDesc_proto_2fGetResourceSubCommand_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n!proto/GetResourceSubCommand.proto\"\027\n\025G"
    "etResourceSubCommandb\006proto3", 68);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "proto/GetResourceSubCommand.proto", &protobuf_RegisterTypes);
  GetResourceSubCommand::default_instance_ = new GetResourceSubCommand();
  GetResourceSubCommand::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_proto_2fGetResourceSubCommand_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_proto_2fGetResourceSubCommand_2eproto {
  StaticDescriptorInitializer_proto_2fGetResourceSubCommand_2eproto() {
    protobuf_AddDesc_proto_2fGetResourceSubCommand_2eproto();
  }
} static_descriptor_initializer_proto_2fGetResourceSubCommand_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GetResourceSubCommand::GetResourceSubCommand()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:GetResourceSubCommand)
}

void GetResourceSubCommand::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

GetResourceSubCommand::GetResourceSubCommand(const GetResourceSubCommand& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:GetResourceSubCommand)
}

void GetResourceSubCommand::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

GetResourceSubCommand::~GetResourceSubCommand() {
  // @@protoc_insertion_point(destructor:GetResourceSubCommand)
  SharedDtor();
}

void GetResourceSubCommand::SharedDtor() {
  if (this != default_instance_) {
  }
}

void GetResourceSubCommand::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GetResourceSubCommand::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return GetResourceSubCommand_descriptor_;
}

const GetResourceSubCommand& GetResourceSubCommand::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_proto_2fGetResourceSubCommand_2eproto();
  return *default_instance_;
}

GetResourceSubCommand* GetResourceSubCommand::default_instance_ = NULL;

GetResourceSubCommand* GetResourceSubCommand::New(::google::protobuf::Arena* arena) const {
  GetResourceSubCommand* n = new GetResourceSubCommand;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void GetResourceSubCommand::Clear() {
}

bool GetResourceSubCommand::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:GetResourceSubCommand)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0 ||
        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
  }
success:
  // @@protoc_insertion_point(parse_success:GetResourceSubCommand)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:GetResourceSubCommand)
  return false;
#undef DO_
}

void GetResourceSubCommand::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:GetResourceSubCommand)
  // @@protoc_insertion_point(serialize_end:GetResourceSubCommand)
}

::google::protobuf::uint8* GetResourceSubCommand::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:GetResourceSubCommand)
  // @@protoc_insertion_point(serialize_to_array_end:GetResourceSubCommand)
  return target;
}

int GetResourceSubCommand::ByteSize() const {
  int total_size = 0;

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GetResourceSubCommand::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const GetResourceSubCommand* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const GetResourceSubCommand>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void GetResourceSubCommand::MergeFrom(const GetResourceSubCommand& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
}

void GetResourceSubCommand::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetResourceSubCommand::CopyFrom(const GetResourceSubCommand& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetResourceSubCommand::IsInitialized() const {

  return true;
}

void GetResourceSubCommand::Swap(GetResourceSubCommand* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GetResourceSubCommand::InternalSwap(GetResourceSubCommand* other) {
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata GetResourceSubCommand::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = GetResourceSubCommand_descriptor_;
  metadata.reflection = GetResourceSubCommand_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// GetResourceSubCommand

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
