// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/SystemSubCommand.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "proto/SystemSubCommand.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* SystemSubCommand_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SystemSubCommand_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_proto_2fSystemSubCommand_2eproto() {
  protobuf_AddDesc_proto_2fSystemSubCommand_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "proto/SystemSubCommand.proto");
  GOOGLE_CHECK(file != NULL);
  SystemSubCommand_descriptor_ = file->message_type(0);
  static const int SystemSubCommand_offsets_[1] = {
  };
  SystemSubCommand_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      SystemSubCommand_descriptor_,
      SystemSubCommand::default_instance_,
      SystemSubCommand_offsets_,
      -1,
      -1,
      -1,
      sizeof(SystemSubCommand),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSubCommand, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SystemSubCommand, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_proto_2fSystemSubCommand_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      SystemSubCommand_descriptor_, &SystemSubCommand::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_proto_2fSystemSubCommand_2eproto() {
  delete SystemSubCommand::default_instance_;
  delete SystemSubCommand_reflection_;
}

void protobuf_AddDesc_proto_2fSystemSubCommand_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\034proto/SystemSubCommand.proto\"\022\n\020System"
    "SubCommandb\006proto3", 58);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "proto/SystemSubCommand.proto", &protobuf_RegisterTypes);
  SystemSubCommand::default_instance_ = new SystemSubCommand();
  SystemSubCommand::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_proto_2fSystemSubCommand_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_proto_2fSystemSubCommand_2eproto {
  StaticDescriptorInitializer_proto_2fSystemSubCommand_2eproto() {
    protobuf_AddDesc_proto_2fSystemSubCommand_2eproto();
  }
} static_descriptor_initializer_proto_2fSystemSubCommand_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SystemSubCommand::SystemSubCommand()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:SystemSubCommand)
}

void SystemSubCommand::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

SystemSubCommand::SystemSubCommand(const SystemSubCommand& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:SystemSubCommand)
}

void SystemSubCommand::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

SystemSubCommand::~SystemSubCommand() {
  // @@protoc_insertion_point(destructor:SystemSubCommand)
  SharedDtor();
}

void SystemSubCommand::SharedDtor() {
  if (this != default_instance_) {
  }
}

void SystemSubCommand::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SystemSubCommand::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SystemSubCommand_descriptor_;
}

const SystemSubCommand& SystemSubCommand::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_proto_2fSystemSubCommand_2eproto();
  return *default_instance_;
}

SystemSubCommand* SystemSubCommand::default_instance_ = NULL;

SystemSubCommand* SystemSubCommand::New(::google::protobuf::Arena* arena) const {
  SystemSubCommand* n = new SystemSubCommand;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SystemSubCommand::Clear() {
}

bool SystemSubCommand::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:SystemSubCommand)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0 ||
        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
  }
success:
  // @@protoc_insertion_point(parse_success:SystemSubCommand)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:SystemSubCommand)
  return false;
#undef DO_
}

void SystemSubCommand::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:SystemSubCommand)
  // @@protoc_insertion_point(serialize_end:SystemSubCommand)
}

::google::protobuf::uint8* SystemSubCommand::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:SystemSubCommand)
  // @@protoc_insertion_point(serialize_to_array_end:SystemSubCommand)
  return target;
}

int SystemSubCommand::ByteSize() const {
  int total_size = 0;

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SystemSubCommand::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const SystemSubCommand* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const SystemSubCommand>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SystemSubCommand::MergeFrom(const SystemSubCommand& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
}

void SystemSubCommand::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SystemSubCommand::CopyFrom(const SystemSubCommand& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SystemSubCommand::IsInitialized() const {

  return true;
}

void SystemSubCommand::Swap(SystemSubCommand* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SystemSubCommand::InternalSwap(SystemSubCommand* other) {
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SystemSubCommand::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SystemSubCommand_descriptor_;
  metadata.reflection = SystemSubCommand_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SystemSubCommand

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
