// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ValueSettedSubCommand.proto

#ifndef PROTOBUF_proto_2fValueSettedSubCommand_2eproto__INCLUDED
#define PROTOBUF_proto_2fValueSettedSubCommand_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_proto_2fValueSettedSubCommand_2eproto();
void protobuf_AssignDesc_proto_2fValueSettedSubCommand_2eproto();
void protobuf_ShutdownFile_proto_2fValueSettedSubCommand_2eproto();

class ValueSettedSubCommand;

// ===================================================================

class ValueSettedSubCommand : public ::google::protobuf::Message {
 public:
  ValueSettedSubCommand();
  virtual ~ValueSettedSubCommand();

  ValueSettedSubCommand(const ValueSettedSubCommand& from);

  inline ValueSettedSubCommand& operator=(const ValueSettedSubCommand& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ValueSettedSubCommand& default_instance();

  enum ValuesCase {
    kOtherValue = 2,
    kCurrentValue = 3,
    kVoltageValue = 4,
    kTemperatureValue = 5,
    VALUES_NOT_SET = 0,
  };

  void Swap(ValueSettedSubCommand* other);

  // implements Message ----------------------------------------------

  inline ValueSettedSubCommand* New() const { return New(NULL); }

  ValueSettedSubCommand* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ValueSettedSubCommand& from);
  void MergeFrom(const ValueSettedSubCommand& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ValueSettedSubCommand* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint32 id() const;
  void set_id(::google::protobuf::uint32 value);

  // optional uint32 otherValue = 2;
  private:
  bool has_othervalue() const;
  public:
  void clear_othervalue();
  static const int kOtherValueFieldNumber = 2;
  ::google::protobuf::uint32 othervalue() const;
  void set_othervalue(::google::protobuf::uint32 value);

  // optional uint32 currentValue = 3;
  private:
  bool has_currentvalue() const;
  public:
  void clear_currentvalue();
  static const int kCurrentValueFieldNumber = 3;
  ::google::protobuf::uint32 currentvalue() const;
  void set_currentvalue(::google::protobuf::uint32 value);

  // optional uint32 voltageValue = 4;
  private:
  bool has_voltagevalue() const;
  public:
  void clear_voltagevalue();
  static const int kVoltageValueFieldNumber = 4;
  ::google::protobuf::uint32 voltagevalue() const;
  void set_voltagevalue(::google::protobuf::uint32 value);

  // optional float temperatureValue = 5;
  private:
  bool has_temperaturevalue() const;
  public:
  void clear_temperaturevalue();
  static const int kTemperatureValueFieldNumber = 5;
  float temperaturevalue() const;
  void set_temperaturevalue(float value);

  // optional uint64 dateSeconds = 6;
  void clear_dateseconds();
  static const int kDateSecondsFieldNumber = 6;
  ::google::protobuf::uint64 dateseconds() const;
  void set_dateseconds(::google::protobuf::uint64 value);

  ValuesCase values_case() const;
  // @@protoc_insertion_point(class_scope:ValueSettedSubCommand)
 private:
  inline void set_has_othervalue();
  inline void set_has_currentvalue();
  inline void set_has_voltagevalue();
  inline void set_has_temperaturevalue();

  inline bool has_values() const;
  void clear_values();
  inline void clear_has_values();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint64 dateseconds_;
  ::google::protobuf::uint32 id_;
  union ValuesUnion {
    ValuesUnion() {}
    ::google::protobuf::uint32 othervalue_;
    ::google::protobuf::uint32 currentvalue_;
    ::google::protobuf::uint32 voltagevalue_;
    float temperaturevalue_;
  } values_;
  mutable int _cached_size_;
  ::google::protobuf::uint32 _oneof_case_[1];

  friend void  protobuf_AddDesc_proto_2fValueSettedSubCommand_2eproto();
  friend void protobuf_AssignDesc_proto_2fValueSettedSubCommand_2eproto();
  friend void protobuf_ShutdownFile_proto_2fValueSettedSubCommand_2eproto();

  void InitAsDefaultInstance();
  static ValueSettedSubCommand* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// ValueSettedSubCommand

// optional uint32 id = 1;
inline void ValueSettedSubCommand::clear_id() {
  id_ = 0u;
}
inline ::google::protobuf::uint32 ValueSettedSubCommand::id() const {
  // @@protoc_insertion_point(field_get:ValueSettedSubCommand.id)
  return id_;
}
inline void ValueSettedSubCommand::set_id(::google::protobuf::uint32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:ValueSettedSubCommand.id)
}

// optional uint32 otherValue = 2;
inline bool ValueSettedSubCommand::has_othervalue() const {
  return values_case() == kOtherValue;
}
inline void ValueSettedSubCommand::set_has_othervalue() {
  _oneof_case_[0] = kOtherValue;
}
inline void ValueSettedSubCommand::clear_othervalue() {
  if (has_othervalue()) {
    values_.othervalue_ = 0u;
    clear_has_values();
  }
}
inline ::google::protobuf::uint32 ValueSettedSubCommand::othervalue() const {
  // @@protoc_insertion_point(field_get:ValueSettedSubCommand.otherValue)
  if (has_othervalue()) {
    return values_.othervalue_;
  }
  return 0u;
}
inline void ValueSettedSubCommand::set_othervalue(::google::protobuf::uint32 value) {
  if (!has_othervalue()) {
    clear_values();
    set_has_othervalue();
  }
  values_.othervalue_ = value;
  // @@protoc_insertion_point(field_set:ValueSettedSubCommand.otherValue)
}

// optional uint32 currentValue = 3;
inline bool ValueSettedSubCommand::has_currentvalue() const {
  return values_case() == kCurrentValue;
}
inline void ValueSettedSubCommand::set_has_currentvalue() {
  _oneof_case_[0] = kCurrentValue;
}
inline void ValueSettedSubCommand::clear_currentvalue() {
  if (has_currentvalue()) {
    values_.currentvalue_ = 0u;
    clear_has_values();
  }
}
inline ::google::protobuf::uint32 ValueSettedSubCommand::currentvalue() const {
  // @@protoc_insertion_point(field_get:ValueSettedSubCommand.currentValue)
  if (has_currentvalue()) {
    return values_.currentvalue_;
  }
  return 0u;
}
inline void ValueSettedSubCommand::set_currentvalue(::google::protobuf::uint32 value) {
  if (!has_currentvalue()) {
    clear_values();
    set_has_currentvalue();
  }
  values_.currentvalue_ = value;
  // @@protoc_insertion_point(field_set:ValueSettedSubCommand.currentValue)
}

// optional uint32 voltageValue = 4;
inline bool ValueSettedSubCommand::has_voltagevalue() const {
  return values_case() == kVoltageValue;
}
inline void ValueSettedSubCommand::set_has_voltagevalue() {
  _oneof_case_[0] = kVoltageValue;
}
inline void ValueSettedSubCommand::clear_voltagevalue() {
  if (has_voltagevalue()) {
    values_.voltagevalue_ = 0u;
    clear_has_values();
  }
}
inline ::google::protobuf::uint32 ValueSettedSubCommand::voltagevalue() const {
  // @@protoc_insertion_point(field_get:ValueSettedSubCommand.voltageValue)
  if (has_voltagevalue()) {
    return values_.voltagevalue_;
  }
  return 0u;
}
inline void ValueSettedSubCommand::set_voltagevalue(::google::protobuf::uint32 value) {
  if (!has_voltagevalue()) {
    clear_values();
    set_has_voltagevalue();
  }
  values_.voltagevalue_ = value;
  // @@protoc_insertion_point(field_set:ValueSettedSubCommand.voltageValue)
}

// optional float temperatureValue = 5;
inline bool ValueSettedSubCommand::has_temperaturevalue() const {
  return values_case() == kTemperatureValue;
}
inline void ValueSettedSubCommand::set_has_temperaturevalue() {
  _oneof_case_[0] = kTemperatureValue;
}
inline void ValueSettedSubCommand::clear_temperaturevalue() {
  if (has_temperaturevalue()) {
    values_.temperaturevalue_ = 0;
    clear_has_values();
  }
}
inline float ValueSettedSubCommand::temperaturevalue() const {
  // @@protoc_insertion_point(field_get:ValueSettedSubCommand.temperatureValue)
  if (has_temperaturevalue()) {
    return values_.temperaturevalue_;
  }
  return 0;
}
inline void ValueSettedSubCommand::set_temperaturevalue(float value) {
  if (!has_temperaturevalue()) {
    clear_values();
    set_has_temperaturevalue();
  }
  values_.temperaturevalue_ = value;
  // @@protoc_insertion_point(field_set:ValueSettedSubCommand.temperatureValue)
}

// optional uint64 dateSeconds = 6;
inline void ValueSettedSubCommand::clear_dateseconds() {
  dateseconds_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 ValueSettedSubCommand::dateseconds() const {
  // @@protoc_insertion_point(field_get:ValueSettedSubCommand.dateSeconds)
  return dateseconds_;
}
inline void ValueSettedSubCommand::set_dateseconds(::google::protobuf::uint64 value) {
  
  dateseconds_ = value;
  // @@protoc_insertion_point(field_set:ValueSettedSubCommand.dateSeconds)
}

inline bool ValueSettedSubCommand::has_values() const {
  return values_case() != VALUES_NOT_SET;
}
inline void ValueSettedSubCommand::clear_has_values() {
  _oneof_case_[0] = VALUES_NOT_SET;
}
inline ValueSettedSubCommand::ValuesCase ValueSettedSubCommand::values_case() const {
  return ValueSettedSubCommand::ValuesCase(_oneof_case_[0]);
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_proto_2fValueSettedSubCommand_2eproto__INCLUDED
