// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ClientCommandBuff.proto

#import "GPBProtocolBuffers_RuntimeSupport.h"
#import "proto/ClientCommandBuff.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma mark - ClientCommandBuffRoot

@implementation ClientCommandBuffRoot

@end

#pragma mark - ClientCommandBuffRoot_FileDescriptor

static GPBFileDescriptor *ClientCommandBuffRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - ClientCommandBuff

@implementation ClientCommandBuff


typedef struct ClientCommandBuff__storage_ {
  uint32_t _has_storage_[0];
} ClientCommandBuff__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[ClientCommandBuff class]
                                     rootClass:[ClientCommandBuffRoot class]
                                          file:ClientCommandBuffRoot_FileDescriptor()
                                        fields:NULL
                                    fieldCount:0
                                        oneofs:NULL
                                    oneofCount:0
                                         enums:NULL
                                     enumCount:0
                                        ranges:NULL
                                    rangeCount:0
                                   storageSize:sizeof(ClientCommandBuff__storage_)
                                    wireFormat:NO];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


// @@protoc_insertion_point(global_scope)
