// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/CommandBuff.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN

@class ManagerSubCommand;
@class SetValueSubCommand;
@class SystemSubCommand;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - CommandBuffRoot

@interface CommandBuffRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - CommandBuff

typedef GPB_ENUM(CommandBuff_FieldNumber) {
  CommandBuff_FieldNumber_SetValueSubCommand = 1,
  CommandBuff_FieldNumber_ManagerSubCommand = 2,
  CommandBuff_FieldNumber_SystemSubCommand = 3,
};

typedef GPB_ENUM(CommandBuff_SubCommand_OneOfCase) {
  CommandBuff_SubCommand_OneOfCase_GPBUnsetOneOfCase = 0,
  CommandBuff_SubCommand_OneOfCase_SetValueSubCommand = 1,
  CommandBuff_SubCommand_OneOfCase_ManagerSubCommand = 2,
  CommandBuff_SubCommand_OneOfCase_SystemSubCommand = 3,
};

@interface CommandBuff : GPBMessage

@property(nonatomic, readonly) CommandBuff_SubCommand_OneOfCase subCommandOneOfCase;

@property(nonatomic, readwrite, strong, null_resettable) SetValueSubCommand *setValueSubCommand;

@property(nonatomic, readwrite, strong, null_resettable) ManagerSubCommand *managerSubCommand;

@property(nonatomic, readwrite, strong, null_resettable) SystemSubCommand *systemSubCommand;

@end

void CommandBuff_ClearSubCommandOneOfCase(CommandBuff *message);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
