// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/CommandBuff.proto

#import "GPBProtocolBuffers_RuntimeSupport.h"
#import "proto/CommandBuff.pbobjc.h"
#import "proto/SetValueSubCommand.pbobjc.h"
#import "proto/SystemSubCommand.pbobjc.h"
#import "proto/ManagerSubCommand.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma mark - CommandBuffRoot

@implementation CommandBuffRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[SetValueSubCommandRoot extensionRegistry]];
    [registry addExtensions:[SystemSubCommandRoot extensionRegistry]];
    [registry addExtensions:[ManagerSubCommandRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - CommandBuffRoot_FileDescriptor

static GPBFileDescriptor *CommandBuffRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - CommandBuff

@implementation CommandBuff

@dynamic subCommandOneOfCase;
@dynamic setValueSubCommand;
@dynamic managerSubCommand;
@dynamic systemSubCommand;

typedef struct CommandBuff__storage_ {
  uint32_t _has_storage_[2];
  SetValueSubCommand *setValueSubCommand;
  ManagerSubCommand *managerSubCommand;
  SystemSubCommand *systemSubCommand;
} CommandBuff__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageOneofDescription oneofs[] = {
      {
        .name = "subCommand",
        .index = -1,
      },
    };
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "setValueSubCommand",
        .number = CommandBuff_FieldNumber_SetValueSubCommand,
        .hasIndex = -1,
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
        .offset = offsetof(CommandBuff__storage_, setValueSubCommand),
        .defaultValue.valueMessage = nil,
        .dataTypeSpecific.className = GPBStringifySymbol(SetValueSubCommand),
        .fieldOptions = NULL,
      },
      {
        .name = "managerSubCommand",
        .number = CommandBuff_FieldNumber_ManagerSubCommand,
        .hasIndex = -1,
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
        .offset = offsetof(CommandBuff__storage_, managerSubCommand),
        .defaultValue.valueMessage = nil,
        .dataTypeSpecific.className = GPBStringifySymbol(ManagerSubCommand),
        .fieldOptions = NULL,
      },
      {
        .name = "systemSubCommand",
        .number = CommandBuff_FieldNumber_SystemSubCommand,
        .hasIndex = -1,
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
        .offset = offsetof(CommandBuff__storage_, systemSubCommand),
        .defaultValue.valueMessage = nil,
        .dataTypeSpecific.className = GPBStringifySymbol(SystemSubCommand),
        .fieldOptions = NULL,
      },
    };
#if GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    const char *extraTextFormatInfo = NULL;
#else
    static const char *extraTextFormatInfo = "\003\001\022\000\002\021\000\003P\000";
#endif  // GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[CommandBuff class]
                                     rootClass:[CommandBuffRoot class]
                                          file:CommandBuffRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                        oneofs:oneofs
                                    oneofCount:sizeof(oneofs) / sizeof(GPBMessageOneofDescription)
                                         enums:NULL
                                     enumCount:0
                                        ranges:NULL
                                    rangeCount:0
                                   storageSize:sizeof(CommandBuff__storage_)
                                    wireFormat:NO
                           extraTextFormatInfo:extraTextFormatInfo];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

void CommandBuff_ClearSubCommandOneOfCase(CommandBuff *message) {
  GPBDescriptor *descriptor = [message descriptor];
  GPBOneofDescriptor *oneof = descriptor->oneofs_[0];
  GPBMaybeClearOneof(message, oneof, 0);
}

// @@protoc_insertion_point(global_scope)
