// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ServerCommandBuff.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN

@class GetResourceSubCommand;
@class SetValueSubCommand;
@class ValueSettedSubCommand;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ServerCommandBuffRoot

@interface ServerCommandBuffRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - ServerCommandBuff

typedef GPB_ENUM(ServerCommandBuff_FieldNumber) {
  ServerCommandBuff_FieldNumber_SetValueSubCommand = 1,
  ServerCommandBuff_FieldNumber_ValueSettedSubCommand = 2,
  ServerCommandBuff_FieldNumber_GetResourceSubCommand = 3,
};

typedef GPB_ENUM(ServerCommandBuff_SubCommand_OneOfCase) {
  ServerCommandBuff_SubCommand_OneOfCase_GPBUnsetOneOfCase = 0,
  ServerCommandBuff_SubCommand_OneOfCase_SetValueSubCommand = 1,
  ServerCommandBuff_SubCommand_OneOfCase_ValueSettedSubCommand = 2,
  ServerCommandBuff_SubCommand_OneOfCase_GetResourceSubCommand = 3,
};

@interface ServerCommandBuff : GPBMessage

@property(nonatomic, readonly) ServerCommandBuff_SubCommand_OneOfCase subCommandOneOfCase;

@property(nonatomic, readwrite, strong, null_resettable) SetValueSubCommand *setValueSubCommand;

@property(nonatomic, readwrite, strong, null_resettable) ValueSettedSubCommand *valueSettedSubCommand;

@property(nonatomic, readwrite, strong, null_resettable) GetResourceSubCommand *getResourceSubCommand;

@end

void ServerCommandBuff_ClearSubCommandOneOfCase(ServerCommandBuff *message);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
