// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/SetValueSubCommand.proto

#import "GPBProtocolBuffers_RuntimeSupport.h"
#import "proto/SetValueSubCommand.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma mark - SetValueSubCommandRoot

@implementation SetValueSubCommandRoot

@end

#pragma mark - SetValueSubCommandRoot_FileDescriptor

static GPBFileDescriptor *SetValueSubCommandRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - SetValueSubCommand

@implementation SetValueSubCommand

@dynamic valuesOneOfCase;
@dynamic id_p;
@dynamic otherValue;
@dynamic userId;

typedef struct SetValueSubCommand__storage_ {
  uint32_t _has_storage_[2];
  uint32_t id_p;
  uint32_t otherValue;
  uint32_t userId;
} SetValueSubCommand__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageOneofDescription oneofs[] = {
      {
        .name = "values",
        .index = -1,
      },
    };
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "id_p",
        .number = SetValueSubCommand_FieldNumber_Id_p,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt32,
        .offset = offsetof(SetValueSubCommand__storage_, id_p),
        .defaultValue.valueUInt32 = 0U,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "otherValue",
        .number = SetValueSubCommand_FieldNumber_OtherValue,
        .hasIndex = -1,
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeUInt32,
        .offset = offsetof(SetValueSubCommand__storage_, otherValue),
        .defaultValue.valueUInt32 = 0U,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "userId",
        .number = SetValueSubCommand_FieldNumber_UserId,
        .hasIndex = 2,
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeUInt32,
        .offset = offsetof(SetValueSubCommand__storage_, userId),
        .defaultValue.valueUInt32 = 0U,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
#if GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    const char *extraTextFormatInfo = NULL;
#else
    static const char *extraTextFormatInfo = "\002\002\n\000\003\006\000";
#endif  // GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[SetValueSubCommand class]
                                     rootClass:[SetValueSubCommandRoot class]
                                          file:SetValueSubCommandRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                        oneofs:oneofs
                                    oneofCount:sizeof(oneofs) / sizeof(GPBMessageOneofDescription)
                                         enums:NULL
                                     enumCount:0
                                        ranges:NULL
                                    rangeCount:0
                                   storageSize:sizeof(SetValueSubCommand__storage_)
                                    wireFormat:NO
                           extraTextFormatInfo:extraTextFormatInfo];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

void SetValueSubCommand_ClearValuesOneOfCase(SetValueSubCommand *message) {
  GPBDescriptor *descriptor = [message descriptor];
  GPBOneofDescriptor *oneof = descriptor->oneofs_[0];
  GPBMaybeClearOneof(message, oneof, 0);
}

// @@protoc_insertion_point(global_scope)
