// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/SystemSubCommand.proto

#import "GPBProtocolBuffers_RuntimeSupport.h"
#import "proto/SystemSubCommand.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma mark - SystemSubCommandRoot

@implementation SystemSubCommandRoot

@end

#pragma mark - SystemSubCommandRoot_FileDescriptor

static GPBFileDescriptor *SystemSubCommandRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - SystemSubCommand

@implementation SystemSubCommand


typedef struct SystemSubCommand__storage_ {
  uint32_t _has_storage_[0];
} SystemSubCommand__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[SystemSubCommand class]
                                     rootClass:[SystemSubCommandRoot class]
                                          file:SystemSubCommandRoot_FileDescriptor()
                                        fields:NULL
                                    fieldCount:0
                                        oneofs:NULL
                                    oneofCount:0
                                         enums:NULL
                                     enumCount:0
                                        ranges:NULL
                                    rangeCount:0
                                   storageSize:sizeof(SystemSubCommand__storage_)
                                    wireFormat:NO];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


// @@protoc_insertion_point(global_scope)
