// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ValueSettedSubCommand.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ValueSettedSubCommandRoot

@interface ValueSettedSubCommandRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - ValueSettedSubCommand

typedef GPB_ENUM(ValueSettedSubCommand_FieldNumber) {
  ValueSettedSubCommand_FieldNumber_Id_p = 1,
  ValueSettedSubCommand_FieldNumber_OtherValue = 2,
  ValueSettedSubCommand_FieldNumber_CurrentValue = 3,
  ValueSettedSubCommand_FieldNumber_VoltageValue = 4,
  ValueSettedSubCommand_FieldNumber_TemperatureValue = 5,
  ValueSettedSubCommand_FieldNumber_DateSeconds = 6,
};

typedef GPB_ENUM(ValueSettedSubCommand_Values_OneOfCase) {
  ValueSettedSubCommand_Values_OneOfCase_GPBUnsetOneOfCase = 0,
  ValueSettedSubCommand_Values_OneOfCase_OtherValue = 2,
  ValueSettedSubCommand_Values_OneOfCase_CurrentValue = 3,
  ValueSettedSubCommand_Values_OneOfCase_VoltageValue = 4,
  ValueSettedSubCommand_Values_OneOfCase_TemperatureValue = 5,
};

@interface ValueSettedSubCommand : GPBMessage

@property(nonatomic, readwrite) uint32_t id_p;

@property(nonatomic, readonly) ValueSettedSubCommand_Values_OneOfCase valuesOneOfCase;

@property(nonatomic, readwrite) uint32_t otherValue;

@property(nonatomic, readwrite) uint32_t currentValue;

@property(nonatomic, readwrite) uint32_t voltageValue;

@property(nonatomic, readwrite) float temperatureValue;

@property(nonatomic, readwrite) uint64_t dateSeconds;

@end

void ValueSettedSubCommand_ClearValuesOneOfCase(ValueSettedSubCommand *message);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
