// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ValueSettedSubCommand.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ValueSettedSubCommandRoot

@interface ValueSettedSubCommandRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - ValueSettedSubCommand

typedef GPB_ENUM(ValueSettedSubCommand_FieldNumber) {
  ValueSettedSubCommand_FieldNumber_Id_p = 1,
  ValueSettedSubCommand_FieldNumber_IValue = 2,
  ValueSettedSubCommand_FieldNumber_FValue = 3,
  ValueSettedSubCommand_FieldNumber_UiValue = 4,
};

typedef GPB_ENUM(ValueSettedSubCommand_Values_OneOfCase) {
  ValueSettedSubCommand_Values_OneOfCase_GPBUnsetOneOfCase = 0,
  ValueSettedSubCommand_Values_OneOfCase_IValue = 2,
  ValueSettedSubCommand_Values_OneOfCase_FValue = 3,
  ValueSettedSubCommand_Values_OneOfCase_UiValue = 4,
};

@interface ValueSettedSubCommand : GPBMessage

@property(nonatomic, readwrite) uint32_t id_p;

@property(nonatomic, readonly) ValueSettedSubCommand_Values_OneOfCase valuesOneOfCase;

@property(nonatomic, readwrite) int32_t iValue;

@property(nonatomic, readwrite) float fValue;

@property(nonatomic, readwrite) uint32_t uiValue;

@end

void ValueSettedSubCommand_ClearValuesOneOfCase(ValueSettedSubCommand *message);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
