// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ValueSettedSubCommand.proto

#import "GPBProtocolBuffers_RuntimeSupport.h"
#import "proto/ValueSettedSubCommand.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma mark - ValueSettedSubCommandRoot

@implementation ValueSettedSubCommandRoot

@end

#pragma mark - ValueSettedSubCommandRoot_FileDescriptor

static GPBFileDescriptor *ValueSettedSubCommandRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - ValueSettedSubCommand

@implementation ValueSettedSubCommand

@dynamic valuesOneOfCase;
@dynamic id_p;
@dynamic iValue;
@dynamic fValue;
@dynamic uiValue;

typedef struct ValueSettedSubCommand__storage_ {
  uint32_t _has_storage_[2];
  uint32_t id_p;
  int32_t iValue;
  float fValue;
  uint32_t uiValue;
} ValueSettedSubCommand__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageOneofDescription oneofs[] = {
      {
        .name = "values",
        .index = -1,
      },
    };
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "id_p",
        .number = ValueSettedSubCommand_FieldNumber_Id_p,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt32,
        .offset = offsetof(ValueSettedSubCommand__storage_, id_p),
        .defaultValue.valueUInt32 = 0U,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "iValue",
        .number = ValueSettedSubCommand_FieldNumber_IValue,
        .hasIndex = -1,
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt32,
        .offset = offsetof(ValueSettedSubCommand__storage_, iValue),
        .defaultValue.valueInt32 = 0,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "fValue",
        .number = ValueSettedSubCommand_FieldNumber_FValue,
        .hasIndex = -1,
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeFloat,
        .offset = offsetof(ValueSettedSubCommand__storage_, fValue),
        .defaultValue.valueFloat = 0,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "uiValue",
        .number = ValueSettedSubCommand_FieldNumber_UiValue,
        .hasIndex = -1,
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeUInt32,
        .offset = offsetof(ValueSettedSubCommand__storage_, uiValue),
        .defaultValue.valueUInt32 = 0U,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
#if GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    const char *extraTextFormatInfo = NULL;
#else
    static const char *extraTextFormatInfo = "\003\002\006\000\003\006\000\004\007\000";
#endif  // GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[ValueSettedSubCommand class]
                                     rootClass:[ValueSettedSubCommandRoot class]
                                          file:ValueSettedSubCommandRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                        oneofs:oneofs
                                    oneofCount:sizeof(oneofs) / sizeof(GPBMessageOneofDescription)
                                         enums:NULL
                                     enumCount:0
                                        ranges:NULL
                                    rangeCount:0
                                   storageSize:sizeof(ValueSettedSubCommand__storage_)
                                    wireFormat:NO
                           extraTextFormatInfo:extraTextFormatInfo];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

void ValueSettedSubCommand_ClearValuesOneOfCase(ValueSettedSubCommand *message) {
  GPBDescriptor *descriptor = [message descriptor];
  GPBOneofDescriptor *oneof = descriptor->oneofs_[0];
  GPBMaybeClearOneof(message, oneof, 0);
}

// @@protoc_insertion_point(global_scope)
