// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/GetResourceSubCommand.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from proto/GetResourceSubCommand.proto</summary>
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
public static partial class GetResourceSubCommandReflection {

  #region Descriptor
  /// <summary>File descriptor for proto/GetResourceSubCommand.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static GetResourceSubCommandReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CiFwcm90by9HZXRSZXNvdXJjZVN1YkNvbW1hbmQucHJvdG8iFwoVR2V0UmVz",
          "b3VyY2VTdWJDb21tYW5kYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedCodeInfo(null, new pbr::GeneratedCodeInfo[] {
          new pbr::GeneratedCodeInfo(typeof(global::GetResourceSubCommand), global::GetResourceSubCommand.Parser, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
public sealed partial class GetResourceSubCommand : pb::IMessage<GetResourceSubCommand> {
  private static readonly pb::MessageParser<GetResourceSubCommand> _parser = new pb::MessageParser<GetResourceSubCommand>(() => new GetResourceSubCommand());
  public static pb::MessageParser<GetResourceSubCommand> Parser { get { return _parser; } }

  public static pbr::MessageDescriptor Descriptor {
    get { return global::GetResourceSubCommandReflection.Descriptor.MessageTypes[0]; }
  }

  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  public GetResourceSubCommand() {
    OnConstruction();
  }

  partial void OnConstruction();

  public GetResourceSubCommand(GetResourceSubCommand other) : this() {
  }

  public GetResourceSubCommand Clone() {
    return new GetResourceSubCommand(this);
  }

  public override bool Equals(object other) {
    return Equals(other as GetResourceSubCommand);
  }

  public bool Equals(GetResourceSubCommand other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    return true;
  }

  public override int GetHashCode() {
    int hash = 1;
    return hash;
  }

  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  public void WriteTo(pb::CodedOutputStream output) {
  }

  public int CalculateSize() {
    int size = 0;
    return size;
  }

  public void MergeFrom(GetResourceSubCommand other) {
    if (other == null) {
      return;
    }
  }

  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
      }
    }
  }

}

#endregion


#endregion Designer generated code
