// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/SetValueSubCommand.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from proto/SetValueSubCommand.proto</summary>
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
public static partial class SetValueSubCommandReflection {

  #region Descriptor
  /// <summary>File descriptor for proto/SetValueSubCommand.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static SetValueSubCommandReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Ch5wcm90by9TZXRWYWx1ZVN1YkNvbW1hbmQucHJvdG8iUAoSU2V0VmFsdWVT",
          "dWJDb21tYW5kEgoKAmlkGAEgASgNEhQKCm90aGVyVmFsdWUYAiABKA1IABIO",
          "CgZ1c2VySWQYAyABKA1CCAoGdmFsdWVzYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedCodeInfo(null, new pbr::GeneratedCodeInfo[] {
          new pbr::GeneratedCodeInfo(typeof(global::SetValueSubCommand), global::SetValueSubCommand.Parser, new[]{ "Id", "OtherValue", "UserId" }, new[]{ "Values" }, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
public sealed partial class SetValueSubCommand : pb::IMessage<SetValueSubCommand> {
  private static readonly pb::MessageParser<SetValueSubCommand> _parser = new pb::MessageParser<SetValueSubCommand>(() => new SetValueSubCommand());
  public static pb::MessageParser<SetValueSubCommand> Parser { get { return _parser; } }

  public static pbr::MessageDescriptor Descriptor {
    get { return global::SetValueSubCommandReflection.Descriptor.MessageTypes[0]; }
  }

  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  public SetValueSubCommand() {
    OnConstruction();
  }

  partial void OnConstruction();

  public SetValueSubCommand(SetValueSubCommand other) : this() {
    id_ = other.id_;
    userId_ = other.userId_;
    switch (other.ValuesCase) {
      case ValuesOneofCase.OtherValue:
        OtherValue = other.OtherValue;
        break;
    }

  }

  public SetValueSubCommand Clone() {
    return new SetValueSubCommand(this);
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 1;
  private uint id_;
  public uint Id {
    get { return id_; }
    set {
      id_ = value;
    }
  }

  /// <summary>Field number for the "otherValue" field.</summary>
  public const int OtherValueFieldNumber = 2;
  public uint OtherValue {
    get { return valuesCase_ == ValuesOneofCase.OtherValue ? (uint) values_ : 0; }
    set {
      values_ = value;
      valuesCase_ = ValuesOneofCase.OtherValue;
    }
  }

  /// <summary>Field number for the "userId" field.</summary>
  public const int UserIdFieldNumber = 3;
  private uint userId_;
  public uint UserId {
    get { return userId_; }
    set {
      userId_ = value;
    }
  }

  private object values_;
  /// <summary>Enum of possible cases for the "values" oneof.</summary>
  public enum ValuesOneofCase {
    None = 0,
    OtherValue = 2,
  }
  private ValuesOneofCase valuesCase_ = ValuesOneofCase.None;
  public ValuesOneofCase ValuesCase {
    get { return valuesCase_; }
  }

  public void ClearValues() {
    valuesCase_ = ValuesOneofCase.None;
    values_ = null;
  }

  public override bool Equals(object other) {
    return Equals(other as SetValueSubCommand);
  }

  public bool Equals(SetValueSubCommand other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if (OtherValue != other.OtherValue) return false;
    if (UserId != other.UserId) return false;
    if (ValuesCase != other.ValuesCase) return false;
    return true;
  }

  public override int GetHashCode() {
    int hash = 1;
    if (Id != 0) hash ^= Id.GetHashCode();
    if (valuesCase_ == ValuesOneofCase.OtherValue) hash ^= OtherValue.GetHashCode();
    if (UserId != 0) hash ^= UserId.GetHashCode();
    hash ^= (int) valuesCase_;
    return hash;
  }

  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  public void WriteTo(pb::CodedOutputStream output) {
    if (Id != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Id);
    }
    if (valuesCase_ == ValuesOneofCase.OtherValue) {
      output.WriteRawTag(16);
      output.WriteUInt32(OtherValue);
    }
    if (UserId != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(UserId);
    }
  }

  public int CalculateSize() {
    int size = 0;
    if (Id != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Id);
    }
    if (valuesCase_ == ValuesOneofCase.OtherValue) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(OtherValue);
    }
    if (UserId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(UserId);
    }
    return size;
  }

  public void MergeFrom(SetValueSubCommand other) {
    if (other == null) {
      return;
    }
    if (other.Id != 0) {
      Id = other.Id;
    }
    if (other.UserId != 0) {
      UserId = other.UserId;
    }
    switch (other.ValuesCase) {
      case ValuesOneofCase.OtherValue:
        OtherValue = other.OtherValue;
        break;
    }

  }

  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 8: {
          Id = input.ReadUInt32();
          break;
        }
        case 16: {
          OtherValue = input.ReadUInt32();
          break;
        }
        case 24: {
          UserId = input.ReadUInt32();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
