// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/CommandBuff.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from proto/CommandBuff.proto</summary>
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
public static partial class CommandBuffReflection {

  #region Descriptor
  /// <summary>File descriptor for proto/CommandBuff.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static CommandBuffReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Chdwcm90by9Db21tYW5kQnVmZi5wcm90byKuAQoLQ29tbWFuZEJ1ZmYSMQoS",
          "c2V0VmFsdWVTdWJDb21tYW5kGAEgASgLMhMuU2V0VmFsdWVTdWJDb21tYW5k",
          "SAASLwoRbWFuYWdlclN1YkNvbW1hbmQYAiABKAsyEi5NYW5hZ2VyU3ViQ29t",
          "bWFuZEgAEi0KEFN5c3RlbVN1YkNvbW1hbmQYAyABKAsyES5TeXN0ZW1TdWJD",
          "b21tYW5kSABCDAoKc3ViQ29tbWFuZCJxChJTZXRWYWx1ZVN1YkNvbW1hbmQS",
          "CgoCaWQYASABKA0SEAoGaVZhbHVlGAIgASgFSAASEAoGZlZhbHVlGAMgASgC",
          "SAASEQoHdWlWYWx1ZRgEIAEoDUgAEg4KBnVzZXJJZBgFIAEoDUIICgZ2YWx1",
          "ZXMiEwoRTWFuYWdlclN1YkNvbW1hbmQiEgoQU3lzdGVtU3ViQ29tbWFuZGIG",
          "cHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedCodeInfo(null, new pbr::GeneratedCodeInfo[] {
          new pbr::GeneratedCodeInfo(typeof(global::CommandBuff), global::CommandBuff.Parser, new[]{ "SetValueSubCommand", "ManagerSubCommand", "SystemSubCommand" }, new[]{ "SubCommand" }, null, null),
          new pbr::GeneratedCodeInfo(typeof(global::SetValueSubCommand), global::SetValueSubCommand.Parser, new[]{ "Id", "IValue", "FValue", "UiValue", "UserId" }, new[]{ "Values" }, null, null),
          new pbr::GeneratedCodeInfo(typeof(global::ManagerSubCommand), global::ManagerSubCommand.Parser, null, null, null, null),
          new pbr::GeneratedCodeInfo(typeof(global::SystemSubCommand), global::SystemSubCommand.Parser, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
public sealed partial class CommandBuff : pb::IMessage<CommandBuff> {
  private static readonly pb::MessageParser<CommandBuff> _parser = new pb::MessageParser<CommandBuff>(() => new CommandBuff());
  public static pb::MessageParser<CommandBuff> Parser { get { return _parser; } }

  public static pbr::MessageDescriptor Descriptor {
    get { return global::CommandBuffReflection.Descriptor.MessageTypes[0]; }
  }

  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  public CommandBuff() {
    OnConstruction();
  }

  partial void OnConstruction();

  public CommandBuff(CommandBuff other) : this() {
    switch (other.SubCommandCase) {
      case SubCommandOneofCase.SetValueSubCommand:
        SetValueSubCommand = other.SetValueSubCommand.Clone();
        break;
      case SubCommandOneofCase.ManagerSubCommand:
        ManagerSubCommand = other.ManagerSubCommand.Clone();
        break;
      case SubCommandOneofCase.SystemSubCommand:
        SystemSubCommand = other.SystemSubCommand.Clone();
        break;
    }

  }

  public CommandBuff Clone() {
    return new CommandBuff(this);
  }

  /// <summary>Field number for the "setValueSubCommand" field.</summary>
  public const int SetValueSubCommandFieldNumber = 1;
  public global::SetValueSubCommand SetValueSubCommand {
    get { return subCommandCase_ == SubCommandOneofCase.SetValueSubCommand ? (global::SetValueSubCommand) subCommand_ : null; }
    set {
      subCommand_ = value;
      subCommandCase_ = value == null ? SubCommandOneofCase.None : SubCommandOneofCase.SetValueSubCommand;
    }
  }

  /// <summary>Field number for the "managerSubCommand" field.</summary>
  public const int ManagerSubCommandFieldNumber = 2;
  public global::ManagerSubCommand ManagerSubCommand {
    get { return subCommandCase_ == SubCommandOneofCase.ManagerSubCommand ? (global::ManagerSubCommand) subCommand_ : null; }
    set {
      subCommand_ = value;
      subCommandCase_ = value == null ? SubCommandOneofCase.None : SubCommandOneofCase.ManagerSubCommand;
    }
  }

  /// <summary>Field number for the "SystemSubCommand" field.</summary>
  public const int SystemSubCommandFieldNumber = 3;
  public global::SystemSubCommand SystemSubCommand {
    get { return subCommandCase_ == SubCommandOneofCase.SystemSubCommand ? (global::SystemSubCommand) subCommand_ : null; }
    set {
      subCommand_ = value;
      subCommandCase_ = value == null ? SubCommandOneofCase.None : SubCommandOneofCase.SystemSubCommand;
    }
  }

  private object subCommand_;
  /// <summary>Enum of possible cases for the "subCommand" oneof.</summary>
  public enum SubCommandOneofCase {
    None = 0,
    SetValueSubCommand = 1,
    ManagerSubCommand = 2,
    SystemSubCommand = 3,
  }
  private SubCommandOneofCase subCommandCase_ = SubCommandOneofCase.None;
  public SubCommandOneofCase SubCommandCase {
    get { return subCommandCase_; }
  }

  public void ClearSubCommand() {
    subCommandCase_ = SubCommandOneofCase.None;
    subCommand_ = null;
  }

  public override bool Equals(object other) {
    return Equals(other as CommandBuff);
  }

  public bool Equals(CommandBuff other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(SetValueSubCommand, other.SetValueSubCommand)) return false;
    if (!object.Equals(ManagerSubCommand, other.ManagerSubCommand)) return false;
    if (!object.Equals(SystemSubCommand, other.SystemSubCommand)) return false;
    if (SubCommandCase != other.SubCommandCase) return false;
    return true;
  }

  public override int GetHashCode() {
    int hash = 1;
    if (subCommandCase_ == SubCommandOneofCase.SetValueSubCommand) hash ^= SetValueSubCommand.GetHashCode();
    if (subCommandCase_ == SubCommandOneofCase.ManagerSubCommand) hash ^= ManagerSubCommand.GetHashCode();
    if (subCommandCase_ == SubCommandOneofCase.SystemSubCommand) hash ^= SystemSubCommand.GetHashCode();
    hash ^= (int) subCommandCase_;
    return hash;
  }

  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  public void WriteTo(pb::CodedOutputStream output) {
    if (subCommandCase_ == SubCommandOneofCase.SetValueSubCommand) {
      output.WriteRawTag(10);
      output.WriteMessage(SetValueSubCommand);
    }
    if (subCommandCase_ == SubCommandOneofCase.ManagerSubCommand) {
      output.WriteRawTag(18);
      output.WriteMessage(ManagerSubCommand);
    }
    if (subCommandCase_ == SubCommandOneofCase.SystemSubCommand) {
      output.WriteRawTag(26);
      output.WriteMessage(SystemSubCommand);
    }
  }

  public int CalculateSize() {
    int size = 0;
    if (subCommandCase_ == SubCommandOneofCase.SetValueSubCommand) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(SetValueSubCommand);
    }
    if (subCommandCase_ == SubCommandOneofCase.ManagerSubCommand) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(ManagerSubCommand);
    }
    if (subCommandCase_ == SubCommandOneofCase.SystemSubCommand) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(SystemSubCommand);
    }
    return size;
  }

  public void MergeFrom(CommandBuff other) {
    if (other == null) {
      return;
    }
    switch (other.SubCommandCase) {
      case SubCommandOneofCase.SetValueSubCommand:
        SetValueSubCommand = other.SetValueSubCommand;
        break;
      case SubCommandOneofCase.ManagerSubCommand:
        ManagerSubCommand = other.ManagerSubCommand;
        break;
      case SubCommandOneofCase.SystemSubCommand:
        SystemSubCommand = other.SystemSubCommand;
        break;
    }

  }

  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 10: {
          global::SetValueSubCommand subBuilder = new global::SetValueSubCommand();
          if (subCommandCase_ == SubCommandOneofCase.SetValueSubCommand) {
            subBuilder.MergeFrom(SetValueSubCommand);
          }
          input.ReadMessage(subBuilder);
          SetValueSubCommand = subBuilder;
          break;
        }
        case 18: {
          global::ManagerSubCommand subBuilder = new global::ManagerSubCommand();
          if (subCommandCase_ == SubCommandOneofCase.ManagerSubCommand) {
            subBuilder.MergeFrom(ManagerSubCommand);
          }
          input.ReadMessage(subBuilder);
          ManagerSubCommand = subBuilder;
          break;
        }
        case 26: {
          global::SystemSubCommand subBuilder = new global::SystemSubCommand();
          if (subCommandCase_ == SubCommandOneofCase.SystemSubCommand) {
            subBuilder.MergeFrom(SystemSubCommand);
          }
          input.ReadMessage(subBuilder);
          SystemSubCommand = subBuilder;
          break;
        }
      }
    }
  }

}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
public sealed partial class SetValueSubCommand : pb::IMessage<SetValueSubCommand> {
  private static readonly pb::MessageParser<SetValueSubCommand> _parser = new pb::MessageParser<SetValueSubCommand>(() => new SetValueSubCommand());
  public static pb::MessageParser<SetValueSubCommand> Parser { get { return _parser; } }

  public static pbr::MessageDescriptor Descriptor {
    get { return global::CommandBuffReflection.Descriptor.MessageTypes[1]; }
  }

  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  public SetValueSubCommand() {
    OnConstruction();
  }

  partial void OnConstruction();

  public SetValueSubCommand(SetValueSubCommand other) : this() {
    id_ = other.id_;
    userId_ = other.userId_;
    switch (other.ValuesCase) {
      case ValuesOneofCase.IValue:
        IValue = other.IValue;
        break;
      case ValuesOneofCase.FValue:
        FValue = other.FValue;
        break;
      case ValuesOneofCase.UiValue:
        UiValue = other.UiValue;
        break;
    }

  }

  public SetValueSubCommand Clone() {
    return new SetValueSubCommand(this);
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 1;
  private uint id_;
  public uint Id {
    get { return id_; }
    set {
      id_ = value;
    }
  }

  /// <summary>Field number for the "iValue" field.</summary>
  public const int IValueFieldNumber = 2;
  public int IValue {
    get { return valuesCase_ == ValuesOneofCase.IValue ? (int) values_ : 0; }
    set {
      values_ = value;
      valuesCase_ = ValuesOneofCase.IValue;
    }
  }

  /// <summary>Field number for the "fValue" field.</summary>
  public const int FValueFieldNumber = 3;
  public float FValue {
    get { return valuesCase_ == ValuesOneofCase.FValue ? (float) values_ : 0F; }
    set {
      values_ = value;
      valuesCase_ = ValuesOneofCase.FValue;
    }
  }

  /// <summary>Field number for the "uiValue" field.</summary>
  public const int UiValueFieldNumber = 4;
  public uint UiValue {
    get { return valuesCase_ == ValuesOneofCase.UiValue ? (uint) values_ : 0; }
    set {
      values_ = value;
      valuesCase_ = ValuesOneofCase.UiValue;
    }
  }

  /// <summary>Field number for the "userId" field.</summary>
  public const int UserIdFieldNumber = 5;
  private uint userId_;
  public uint UserId {
    get { return userId_; }
    set {
      userId_ = value;
    }
  }

  private object values_;
  /// <summary>Enum of possible cases for the "values" oneof.</summary>
  public enum ValuesOneofCase {
    None = 0,
    IValue = 2,
    FValue = 3,
    UiValue = 4,
  }
  private ValuesOneofCase valuesCase_ = ValuesOneofCase.None;
  public ValuesOneofCase ValuesCase {
    get { return valuesCase_; }
  }

  public void ClearValues() {
    valuesCase_ = ValuesOneofCase.None;
    values_ = null;
  }

  public override bool Equals(object other) {
    return Equals(other as SetValueSubCommand);
  }

  public bool Equals(SetValueSubCommand other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if (IValue != other.IValue) return false;
    if (FValue != other.FValue) return false;
    if (UiValue != other.UiValue) return false;
    if (UserId != other.UserId) return false;
    if (ValuesCase != other.ValuesCase) return false;
    return true;
  }

  public override int GetHashCode() {
    int hash = 1;
    if (Id != 0) hash ^= Id.GetHashCode();
    if (valuesCase_ == ValuesOneofCase.IValue) hash ^= IValue.GetHashCode();
    if (valuesCase_ == ValuesOneofCase.FValue) hash ^= FValue.GetHashCode();
    if (valuesCase_ == ValuesOneofCase.UiValue) hash ^= UiValue.GetHashCode();
    if (UserId != 0) hash ^= UserId.GetHashCode();
    hash ^= (int) valuesCase_;
    return hash;
  }

  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  public void WriteTo(pb::CodedOutputStream output) {
    if (Id != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Id);
    }
    if (valuesCase_ == ValuesOneofCase.IValue) {
      output.WriteRawTag(16);
      output.WriteInt32(IValue);
    }
    if (valuesCase_ == ValuesOneofCase.FValue) {
      output.WriteRawTag(29);
      output.WriteFloat(FValue);
    }
    if (valuesCase_ == ValuesOneofCase.UiValue) {
      output.WriteRawTag(32);
      output.WriteUInt32(UiValue);
    }
    if (UserId != 0) {
      output.WriteRawTag(40);
      output.WriteUInt32(UserId);
    }
  }

  public int CalculateSize() {
    int size = 0;
    if (Id != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Id);
    }
    if (valuesCase_ == ValuesOneofCase.IValue) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(IValue);
    }
    if (valuesCase_ == ValuesOneofCase.FValue) {
      size += 1 + 4;
    }
    if (valuesCase_ == ValuesOneofCase.UiValue) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(UiValue);
    }
    if (UserId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(UserId);
    }
    return size;
  }

  public void MergeFrom(SetValueSubCommand other) {
    if (other == null) {
      return;
    }
    if (other.Id != 0) {
      Id = other.Id;
    }
    if (other.UserId != 0) {
      UserId = other.UserId;
    }
    switch (other.ValuesCase) {
      case ValuesOneofCase.IValue:
        IValue = other.IValue;
        break;
      case ValuesOneofCase.FValue:
        FValue = other.FValue;
        break;
      case ValuesOneofCase.UiValue:
        UiValue = other.UiValue;
        break;
    }

  }

  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 8: {
          Id = input.ReadUInt32();
          break;
        }
        case 16: {
          IValue = input.ReadInt32();
          break;
        }
        case 29: {
          FValue = input.ReadFloat();
          break;
        }
        case 32: {
          UiValue = input.ReadUInt32();
          break;
        }
        case 40: {
          UserId = input.ReadUInt32();
          break;
        }
      }
    }
  }

}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
public sealed partial class ManagerSubCommand : pb::IMessage<ManagerSubCommand> {
  private static readonly pb::MessageParser<ManagerSubCommand> _parser = new pb::MessageParser<ManagerSubCommand>(() => new ManagerSubCommand());
  public static pb::MessageParser<ManagerSubCommand> Parser { get { return _parser; } }

  public static pbr::MessageDescriptor Descriptor {
    get { return global::CommandBuffReflection.Descriptor.MessageTypes[2]; }
  }

  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  public ManagerSubCommand() {
    OnConstruction();
  }

  partial void OnConstruction();

  public ManagerSubCommand(ManagerSubCommand other) : this() {
  }

  public ManagerSubCommand Clone() {
    return new ManagerSubCommand(this);
  }

  public override bool Equals(object other) {
    return Equals(other as ManagerSubCommand);
  }

  public bool Equals(ManagerSubCommand other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    return true;
  }

  public override int GetHashCode() {
    int hash = 1;
    return hash;
  }

  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  public void WriteTo(pb::CodedOutputStream output) {
  }

  public int CalculateSize() {
    int size = 0;
    return size;
  }

  public void MergeFrom(ManagerSubCommand other) {
    if (other == null) {
      return;
    }
  }

  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
      }
    }
  }

}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
public sealed partial class SystemSubCommand : pb::IMessage<SystemSubCommand> {
  private static readonly pb::MessageParser<SystemSubCommand> _parser = new pb::MessageParser<SystemSubCommand>(() => new SystemSubCommand());
  public static pb::MessageParser<SystemSubCommand> Parser { get { return _parser; } }

  public static pbr::MessageDescriptor Descriptor {
    get { return global::CommandBuffReflection.Descriptor.MessageTypes[3]; }
  }

  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  public SystemSubCommand() {
    OnConstruction();
  }

  partial void OnConstruction();

  public SystemSubCommand(SystemSubCommand other) : this() {
  }

  public SystemSubCommand Clone() {
    return new SystemSubCommand(this);
  }

  public override bool Equals(object other) {
    return Equals(other as SystemSubCommand);
  }

  public bool Equals(SystemSubCommand other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    return true;
  }

  public override int GetHashCode() {
    int hash = 1;
    return hash;
  }

  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  public void WriteTo(pb::CodedOutputStream output) {
  }

  public int CalculateSize() {
    int size = 0;
    return size;
  }

  public void MergeFrom(SystemSubCommand other) {
    if (other == null) {
      return;
    }
  }

  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
      }
    }
  }

}

#endregion


#endregion Designer generated code
